[package]
name = "geoconverter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.12", features = ["derive"] }
proj = { version = "0.27.2", features = ["bundled_proj"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.102"
